In [74]:
import torch

In [75]:
a_t = torch.tensor(list(range(9)))

In [76]:
a_t.shape, a_t.storage_offset(), a_t.stride()

(torch.Size([9]), 0, (1,))

In [77]:
b = a_t.view(3,3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [78]:
storage_a = a_t.storage()
storage_b = b.storage()
id(storage_a[0]) == id(storage_b[0]),id(storage_b[0]),id(storage_a[0])

(True, 94902455328032, 94902455328032)

In [79]:
c = b[1:,1:]
# c.size=(2,2), c.storage_offset() = 4 c.stride()=(3,1)
c.shape, c.storage_offset(), c.stride()

(torch.Size([2, 2]), 4, (3, 1))

### 3ds

In [96]:
c = c.type(torch.float32)
c.cos()

tensor([[-0.6536,  0.2837],
        [ 0.7539, -0.1455]])

In [97]:
# in place
c.cos_()
c

tensor([[-0.6536,  0.2837],
        [ 0.7539, -0.1455]])